 trigger:
 - main
    
 pool:
   vmImage: ubuntu-latest
    
 steps:
 - task: UseDotNet@2
   displayName: Use Dotnet 10
   inputs:
    version: "10.0.x"
    
 - script: dotnet clean src/Application.csproj
   displayName: "dotnet clean"

 - script: dotnet test tests/Application.Tests.csproj
   displayName: "dotnet test"

 - script: dotnet build src/Application.csproj
   displayName: "dotnet build"

 - script: dotnet publish src/Application.csproj
   displayName: "dotnet publish"
    
